# Welcome to Jekyll!

# Site settings
title: Jaseem Abid
email: jaseemabid@gmail.com

description: >
  Jaseem Abid's personal website

baseurl: ""
url: "http://yourdomain.com"
username: jaseemabid

# Build settings
markdown: kramdown
