# Welcome to Jekyll!

# Site settings
title: Jaseem Abid
email: jaseemabid@gmail.com

description: Jaseem Abid's blogs and musings

baseurl: ""
url: "https://blog.jabid.in"
username: jaseemabid

# Build settings
markdown: kramdown
